In [1]:
import numpy as np


In [10]:
matrix_1 = np.array([[12,34],[34,76]])
print(matrix_1)

[[12 34]
 [34 76]]


In [11]:

matrix_1.shape

(2, 2)

In [12]:
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_3 = np.random.rand(3,3)
print(matrix_3)


[[0.26789922 0.47737754 0.52859322]
 [0.54700917 0.18813166 0.75849244]
 [0.08984874 0.97853331 0.70857558]]


In [17]:
matrix_int = np.random.randint(10,size=(3,3))
print(matrix_int)

[[4 7 8]
 [4 6 8]
 [5 2 6]]


In [18]:
print(matrix_2*matrix_int)

[[ 4 14 24]
 [16 30 48]
 [35 16 54]]


In [24]:
matrix_4 = np.ones((2,3),dtype = int)
print(matrix_4)

[[1 1 1]
 [1 1 1]]


**null matrix**

In [25]:
null_matrix = np.zeros((3,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**identity matrix**

In [28]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**transpose of matrix**

In [30]:
a = np.random.randint(100,size=(27,17))
print(a)

[[72 83 45 92 75 41 80 88 46 69 80 32 98 29 59 34 47]
 [96 60  0 62 47 83 11 53  8 86 61 11 17 90 71 53 16]
 [17 42 21  3 29 25 82  6 82 95 55 89 30 76 94 56 23]
 [17 33 68 84 98 77 80 35 89 65 95 91 32 51 33 25 40]
 [47 45 66 78  8 70 65 32 84 18 88 38 22 62 15 91 14]
 [87 32 41  2 52 37 65 18 45 61  5 47 15 12 57 89 12]
 [95 34 33 73 40 44 45 22 32 71 90  3 23 55 20 19  7]
 [78 18  5 86 34 84 44  3 99 99  9 28 61 19 66 63 69]
 [56  7 21 66 54 90 37 79  4 90 98 15  2 21 69  7 42]
 [39 56 47 99 68 83 21 85 78 69  6 68 66 20 93 34 64]
 [30 48 41 84 76 16 63 20  4 85 67 87 67 38 71 67 65]
 [96 83 11 22 39 17  7 58 75 45  2 56 13 80 97 57 59]
 [40 65 39 25 74 57 23 63 15 39 81 90 14 21 47 87 80]
 [78 93 17  8 16 32 43 14 65 66 74 52 54 27 12 21 77]
 [12 41 17 48 77 90 57 37 60 64 57 29 83 41 84 15 89]
 [54 64 34 21 73 25 24 40 37 78 90 24 18 88 85  4 11]
 [23 62 26 67 74 77 47  4 59 18 15 38 72 81 93 30 72]
 [ 0 43 91 33 57  7 19 30 35 77 53 37 61 89  3  9 91]
 [88 69 94 97 71 42 35 15 34

In [32]:
b = np.transpose(a)
print(b)

[[72 96 17 17 47 87 95 78 56 39 30 96 40 78 12 54 23  0 88 65 77 57 34 95
  77 48 18]
 [83 60 42 33 45 32 34 18  7 56 48 83 65 93 41 64 62 43 69 80 98 83 71 31
  82 26 84]
 [45  0 21 68 66 41 33  5 21 47 41 11 39 17 17 34 26 91 94 30 60 92 87 92
  38 42 70]
 [92 62  3 84 78  2 73 86 66 99 84 22 25  8 48 21 67 33 97 11 60 46 22 73
   7 72  8]
 [75 47 29 98  8 52 40 34 54 68 76 39 74 16 77 73 74 57 71 49 88 79 91 20
   8  7 41]
 [41 83 25 77 70 37 44 84 90 83 16 17 57 32 90 25 77  7 42 39 41 77 92 94
  96 51 92]
 [80 11 82 80 65 65 45 44 37 21 63  7 23 43 57 24 47 19 35 66 98 14  8 17
  65 13 89]
 [88 53  6 35 32 18 22  3 79 85 20 58 63 14 37 40  4 30 15 48 87 84 84 72
  93  9 29]
 [46  8 82 89 84 45 32 99  4 78  4 75 15 65 60 37 59 35 34 94 77 49 49 86
   5 64 49]
 [69 86 95 65 18 61 71 99 90 69 85 45 39 66 64 78 18 77 99 59 22 54 43 14
  61 49 66]
 [80 61 55 95 88  5 90  9 98  6 67  2 81 74 57 90 15 53 10 20 53 93 10 98
  73 57 41]
 [32 11 89 91 38 47  3 28 15 68 87 56 90 52 29 24 38 3