In [ ]:
import numpy as np

**matrix addition**

In [ ]:
# 2x2 matrix addition
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.add(a, b))


[[ 6  8]
 [10 12]]


In [ ]:
# 2*3 matrix addition

a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([[5, 6, 7], [7, 8, 9]])

print(np.add(a, b))


[[ 6  8 10]
 [10 12 14]]


**matrix subration**

In [ ]:

# 2x2 matrix subtraction
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.subtract(a, b))

# 2*3 matrix subtraction
a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([[5, 6, 7], [7, 8, 9]])

print(np.subtract(a, b))


[[-4 -4]
 [-4 -4]]
[[-4 -4 -4]
 [-4 -4 -4]]


**matrix multipication with scalar**

In [8]:


# Define a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Define a scalar
scalar = 5

# Multiply the matrix by the scalar
result = matrix * scalar

# Print the result
print(result)


[[ 5 10]
 [15 20]]


**matrix division**

In [9]:


# **Matrix division with scalar**

# Define a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Define a scalar
scalar = 5

# Divide the matrix by the scalar
result = matrix / scalar

# Print the result
print(result)


[[0.2 0.4]
 [0.6 0.8]]
